version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    target-branch: "7.x"
    schedule:
      interval: "monthly"
      time: "22:00"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "7.x"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
