name: PostGreSQL

on:
  push:
    branches:
      - "**"
    paths-ignore:
      - "art/**"
      - "README.md"
  pull_request:
    types: [ready_for_review, synchronize, opened]
    paths-ignore:
      - "art/**"
      - "README.md"

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:9.6
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: powergridtest
        ports:
          - 5433:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    strategy:
      matrix:
        php: [ 8.2, 8.1 ]
        laravel: [ 10.* ]
        dependency-version: [ prefer-stable ]

    name: PHP:${{ matrix.php }} / L:${{ matrix.laravel }}

    if: github.ref != 'refs/heads/todo-tests'

    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          tools: composer:v2
          coverage: none

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: $(composer config cache-files-dir)
          key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Install Composer dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
          rm composer.lock
          composer install

      - name: Install openspout/openspout
        if: matrix.php == '8.2'
        run: composer require openspout/openspout

      - name: PostGreSQL
        run: composer test:pgsql
