name: Test Build

on:
  push:
    branches:
      - "**"
  pull_request:
    types: [ ready_for_review, synchronize, opened ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test-build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
          cache: 'yarn'

      - name: Validate and Install Yarn Dependencies
        run: |
          yarn config set network-timeout 300000
          yarn install --frozen-lockfile --immutable

      - name: Audit Dependencies for Vulnerabilities
        run: yarn audit --level high

      - name: Build
        run: yarn build

      - name: Build Tailwind 4
        run: yarn build:tailwind
