name: Scout Typesense

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: powergridtest
        ports:
          - 3307:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    strategy:
      fail-fast: false
      matrix:
        php: [8.3]
        laravel: [11.*]
        dependency-version: [ prefer-stable ]

    name: PHP:${{ matrix.php }} / L:${{ matrix.laravel }}

    if: github.ref != 'refs/heads/todo-tests'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          tools: composer:v2
          coverage: none

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: $(composer config cache-files-dir)
          key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Install Typesense
        run: |
          curl -O https://dl.typesense.org/releases/26.0/typesense-server-26.0-arm64.deb
          curl -O https://dl.typesense.org/releases/26.0/typesense-server-26.0-amd64.deb
          sudo apt install ./typesense-server-26.0-amd64.deb

      - name: Install Composer dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
          composer require laravel/scout
          composer require typesense/typesense-php
          composer install

      - name: Tests
        run: composer test:typesense
